// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://guykuqowrkmsloyhsqsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1eWt1cW93cmttc2xveWhzcXNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3ODM0MjQsImV4cCI6MjA2OTM1OTQyNH0.GOjPw7QgpI_VuZZxcKmT4D1ZYLGpJVvYEuzTGo2w1Cw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});